### ISSUE TITLE
Foobar don't plays NSFE files

### ISSUE THREAD

**Issue by mvartem** [EterCyber/Foobar2000-Input-Notsofatso#1]
Windows 10, Foobar2000 v1.5.5, Foobar2000-Input-Notsofatso-v1.2

It plays NSF files well, but when i try NSFEs see this: Unable to open item for playback (Seek offset out of range)

![image](https://user-images.githubusercontent.com/70186038/91240131-756d0600-e784-11ea-83d6-fbf4f5c8e356.png)

**Comment by mvartem** [comment]
Yes, i tried that way. When i

**Comment by EterCyber** [comment]
Since the NSFE format is not very different from the NSF format, the NSFE format has been abandoned. I tried to modify the code to support the NSFE format, but failed. Later, I will remove all the code related to the NSFE format.

This issue should not be opened again in the future.
